Bank/Controllers/DealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bank.Models;
using Bank.Services;

namespace Bank.Controllers
{
    [Authorize]
    public class DealController : Controller
    {
        private readonly IProductService _productService;
        private readonly IDealService _dealService;

        public DealController(IProductService productService, IDealService dealService)
        {
            _productService = productService;
            _dealService = dealService;

        }

        public ActionResult Statistics()
        {
            var chartData = _dealService.GetChartViewModel();
            return View(chartData);
        }



        public ActionResult ShowOffer()
        {
            return View();
        }

        // TODO : dealsOFClientList is entites list !! should be viewmodel list
        public ActionResult DealsOfClient(int clientId)
        {
            var dealsOfClientList = _dealService.GetActiveDealsOfClient(clientId);
            return View(dealsOfClientList);

        }

        public ActionResult SelectNewDeal(int clientId)
        {
            return View(clientId);
        }

        [HttpGet]
        public ActionResult NewCredit(int clientId)
        {
            var viewModel = _productService.GetCreditViewModel();
            viewModel.ClientId = clientId;
            return View(viewModel);

        }

        [HttpPost]
        public ActionResult NewCredit(CreditViewModel creditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(creditViewModel);
            }

            _productService.AddCredit(creditViewModel);

            return RedirectToAction("ClientsPage", "Client");

        }

        [HttpGet]
        public ActionResult NewAccount(int clientId)
        {
            var viewModel = _productService.GetBankAccountViewModel();
            viewModel.ClientId = clientId;
            return View(viewModel);

        }

        [HttpPost]
        public ActionResult NewAccount(BankAccountViewModel bankAccountViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bankAccountViewModel);
            }

            _productService.AddAccount(bankAccountViewModel);

            return RedirectToAction("ClientsPage", "Client");
        }

        [HttpGet]
        public ActionResult NewDeposit(int clientId)
        {
            var viewModel = _productService.GetDepositViewModel();
            viewModel.ClientId = clientId;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult NewDeposit(DepositViewModel depositViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(depositViewModel);
            }

            _productService.AddDeposit(depositViewModel);

            return RedirectToAction("ClientsPage", "Client");
        }

        [HttpGet]
        public ActionResult EditCredit(int productId)
        {
            var creditViewModel = _productService.GetCreditViewModelByProductId(productId);
            return View(creditViewModel);
        }

        [HttpPost]
        public ActionResult EditCredit(CreditViewModel creditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(creditViewModel);
            }

            _productService.UpdateCredit(creditViewModel);

            return RedirectToAction("DealsOfClient", new { clientId = creditViewModel.ClientId });
        }

        [HttpGet]
        public ActionResult EditAccount(int productId)
        {
            var accountViewModel = _productService.GetBankAccountViewModelByProductId(productId);
            return View(accountViewModel);
        }

        [HttpPost]
        public ActionResult EditAccount(BankAccountViewModel bankAccountViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bankAccountViewModel);
            }

            _productService.UpdateAccount(bankAccountViewModel);

            return RedirectToAction("DealsOfClient", new { clientId = bankAccountViewModel.ClientId });
        }

        [HttpGet]
        public ActionResult EditDeposit(int productId)
        {
            var depositViewModel = _productService.GetDepositViewModelByProductId(productId);
            return View(depositViewModel);
        }

        [HttpPost]
        public ActionResult EditDeposit(DepositViewModel depositViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(depositViewModel);
            }

            _productService.UpdateDeposit(depositViewModel);

            return RedirectToAction("DealsOfClient", new { clientId = depositViewModel.ClientId });
        }



    }
}

Bank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link runat="server" rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/favicon.ico" type="image/ico" />
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
           @if (Request.IsAuthenticated)
           {
            <span style="font-size: 30px; cursor: pointer; color: white; " onclick="openNav()">&#9776;</span>
           }
        </div>
        <div class="navbar-collapse collapse">
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>


        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="@Url.Action("Statistics","Deal")">Główna</a>
            <a href="@Url.Action("ShowOffer","Deal")">Oferta</a>
            <a href="@Url.Action("ClientsPage","Client")">Klienci</a>
            <a href="@Url.Action("AddClient","Client")">Dodaj klienta</a>
            <a href="#">Inne</a>
        </div>

    <div class="container body-content">
        @RenderBody()
        @*<footer>
            </footer>*@
    </div>


    <script type="text/javascript">
       
        function openNav() {
            $("#mySidenav").css({ width: "250px", height: "100%", opacity: 0.0 }).animate({ opacity: 1.0 }, 2000);
        }

        function closeNav() {
            $("#mySidenav").css({ width: "0", height: "0", opacity: 0.0 });
        }
    </script>



@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>